### ISSUE TITLE
EU Crypt

### ISSUE THREAD

**Issue by PatrickSantoZZ** [CorpseKitten/BDOPlugin#1]
Any Plan to add EU as region?

**Comment by CorpseKitten** [comment]
Heya Patrick, it will be updated to fit EUNA 491 in the near future.

I do not plan to add support for current retail clients as that isn't the aim of this project, it's intended to be paired with Illuminate, which can be found here;

https://github.com/CoolManBob/Illuminate

**Comment by PatrickSantoZZ** [comment]
ahh good ye that should work too. maybe i take a look into this project :)
